### ISSUE TITLE
add prereqs/before you begin doc

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo-mesh#1169]
**Describe the requested changes**
There is currently no real summary of what meshes can be managed by gloo mesh. There should be documentation that calls out which versions of which meshes are supported.

**Link to any relevant existing docs**
There is an existing call out to Istio 1.7 and 1.8 on this page: https://docs.solo.io/gloo-mesh/latest/guides/installing_istio/
Although that helps, it is not intuitive for users to be the only source on the docs of which versions are supported, especially since the link in the navigation is "Installing Istio Multicluster"

**Browser Information**
N/A

**Additional context**
N/A

**Comment by joekelley** [comment]
We can expand this to describe the various versions of Kubernetes and each mesh that Gloo Mesh is compatible with.
