### ISSUE TITLE
Istio Smart DNS

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo-mesh#1179]
**Is your feature request related to a problem? Please describe.**
As of Istio 1.8.x, a new form of optional Smart DNS was introduced outlined by the following [blog post](https://istio.io/latest/blog/2020/dns-proxy/#concluding-thoughts). This will alleviate the need to use the `.global` domain for all multicluster traffic, as the coredns/kubedns config will not need to be modified for each domain.

**Describe the solution you'd like**

- [x] Ensure that gloo-mesh works properly with the new Smart DNS
- [ ] Allow for cusomization of multicluster domains via the API

**Comment by Sathishkunisai** [comment]
Hi @EItanya ,

Is this the only way to enable SmartDNS? Please advise, I am trying to experiment it in my multicluster setup where i have .global defined in SE for several services.

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
 meshConfig:
   defaultConfig:
     proxyMetadata:
       ISTIO_META_DNS_CAPTURE: "true"
