### ISSUE TITLE
Add cleanup steps to guides

### ISSUE THREAD

**Issue by joekelley** [solo-io/gloo-mesh#1190]
When working through the Gloo Mesh guides, it's possible that a user might get into a situation where leftover config from a previous guide affects the expected behavior of a subsequent guide. One example is when navigating from https://docs.solo.io/gloo-mesh/latest/guides/multicluster_communication/ to https://docs.solo.io/gloo-mesh/latest/guides/failover_service_guide/.

We should add a cleanup step to all guides so users can get their clusters back to a clean state.

**Comment by Rachael-Graham** [comment]
Added. For example, see end of page steps in https://docs.solo.io/gloo-mesh-enterprise/main/policies/cors/
