### ISSUE TITLE
Add docs for single-cluster use cases

### ISSUE THREAD

**Issue by joekelley** [solo-io/gloo-mesh#1223]
**Describe the requested changes**
Most of our documentation covers multicluster use-cases of Gloo Mesh. However, there's much value to be had even in single cluster service mesh environments. We should offer some documentation for how to get started with Gloo Mesh on a single cluster and describe how GM features can be leveraged in that scenario.

**Comment by Rachael-Graham** [comment]
Getting started for single-cluster Mesh included in this pr: https://github.com/solo-io/gloo-mesh-enterprise/pull/7300/files#diff-01123c06ed2209a4fdd94018155532f6acdb39a8b64c85ab4fd9509eed7d2362
