### ISSUE TITLE
cannot re-init plugin manager

### ISSUE THREAD

**Issue by joekelley** [solo-io/gloo-mesh#1312]
**Describe the bug**
If you install the plugin manager, uninstall the plugin manager, and then attempt to re-install the plugin manager, you will encounter an error. 

**To Reproduce**
1. meshctl init-plugin-manger
2. meshctl plugin uninstall plugin
3. 👇 
```
❯ meshctl init-plugin-manager
++ mktemp -d
+ cd /var/folders/66/5b1xj_gn1r7c64cfxgj7kmb40000gn/T/tmp.dZiH7ZAp
+ version=v1.0.0-beta5
++ uname
++ tr '[:upper:]' '[:lower:]'
+ os=darwin
+ arch=amd64
+ curl -o plugin -fsSL https://storage.googleapis.com/gloo-mesh-enterprise/meshctl-plugins/plugin/v1.0.0-beta5/meshctl-plugin-darwin-amd64
+ chmod u+x plugin
+ ./plugin index add default https://github.com/solo-io/meshctl-plugin-index.git
Error: index already exists
Error: exit status 1
```

**Expected behavior**
Either the meshctl-plugin install script should be able to handle the case that the index already exists, or we should clean up the plugin index when uninstalling `plugin` such that this error does not occur.

**Additional context**
meshctl 0.12.7

**Comment by ryantking** [comment]
`init-plugin-manager` should require a `-f` to clear everything and reinit if it finds existing files.
