### ISSUE TITLE
Improve documentation for the default RoleBinding

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo-mesh#1343]
**Describe the requested changes**
When Gloo Mesh is deployed a default RoleBinding called `admin-role-binding` is created.
It assumes that the default Kubernetes user is `kubernetes-admin`, but it's not always the case.
In Azure, for example, the default user is called `masterclient`.

We should document this and explain how to update the RoleBinding.

**Comment by joekelley** [comment]
This is described here: https://docs.solo.io/gloo-mesh/latest/guides/using_role_based_api/#admin-role
