### ISSUE TITLE
Discovery artifacts aren't cleaned up after cluster deregistration

### ISSUE THREAD

**Issue by joekelley** [solo-io/gloo-mesh#1376]
**Describe the bug**
After deregistering a remote kubernetes cluster (uninstalling the agent and deleting the corresponding kubernetes cluster resource) there were still discovery artifacts (e.g. a mesh resource) for the remote cluster left on the management cluster.

**To Reproduce**
1. Install gloo mesh enterprise on mgmt-cluster
2. Install Istio on mgmt-cluster and remote-cluster
3. Register mgmt-cluster and remote-cluster
4. Verify that a mesh resource was created for remote-cluster
5. Deregister remote-cluster
6. See that the mesh resource is still around

**Expected behavior**
I would expect the mesh resource from remote-cluster to be cleaned up.

**Additional context**

meshctl 1.0.0, GME 1.0.0

**Comment by ashleywang1** [comment]
I'm not sure how to deregister a remote cluster.
```
meshctl cluster deregister enterprise remote-cluster --remote-context $REMOTE_CONTEXT
```
- will uninstall the remote enterprise-agent chart but not delete the KubernetesCluster CR
```
meshctl cluster deregister enterprise remote-cluster
```
- will delete the KubernetesCluster CR but will not uninstall the remote enterprise-agent chart

**Comment by ashleywang1** [comment]
We should also be removing the networking output artifacts:

Otherwise, when the enterprise-networking pod starts up with Networking input TrafficPolicies, etc, we run into a
```
"error":"Timeout: failed waiting for *v1.Settings Informer to sync"}
```
issue.

To fix this, you need to clean up everything:

```
# Delete the namespaces and their contents too
kubectl delete ns --context $CLUSTER_1 gloo-mesh
kubectl delete ns --context $CLUSTER_2 gloo-mesh

k delete authorizationpolicies.security.istio.io --selector=owner.networking.mesh.gloo.solo.io=gloo-mesh --context $CLUSTER_1
k delete gateways.networking.istio.io --selector=owner.networking.mesh.gloo.solo.io=gloo-mesh --context $CLUSTER_1
k delete envoyfilters.networking.istio.io --selector=owner.networking.mesh.gloo.solo.io=gloo-mesh --context $CLUSTER_1
k delete destinationrules.networking.istio.io --selector=owner.networking.mesh.gloo.solo.io=gloo-mesh --context $CLUSTER_1
k delete serviceentries.networking.istio.io --selector=owner.networking.mesh.gloo.solo.io=gloo-mesh --context $CLUSTER_1
k delete virtualservices.networking.istio.io --selector=owner.networking.mesh.gloo.solo.io=gloo-mesh --context $CLUSTER_1

k delete authorizationpolicies.security.istio.io --selector=owner.networking.mesh.gloo.solo.io=gloo-mesh --context $CLUSTER_2
k delete gateways.networking.istio.io --selector=owner.networking.mesh.gloo.solo.io=gloo-mesh --context $CLUSTER_2
k delete envoyfilters.networking.istio.io --selector=owner.networking.mesh.gloo.solo.io=gloo-mesh --context $CLUSTER_2
k delete destinationrules.networking.istio.io --selector=owner.networking.mesh.gloo.solo.io=gloo-mesh --context $CLUSTER_2
k delete serviceentries.networking.istio.io --selector=owner.networking.mesh.gloo.solo.io=gloo-mesh --context $CLUSTER_2
k delete virtualservices.networking.istio.io --selector=owner.networking.mesh.gloo.solo.io=gloo-mesh --context $CLUSTER_2
```

**Comment by EItanya** [comment]
Discovery resources which belong to a cluster whose `KubernetesCluster` resource has been removed are now cleaned up
