### ISSUE TITLE
Add ability to customize annotations and labels for the helm chart

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo-mesh#1383]
For any of the services (or resources in general -- but specifically services) we should be able to append annotations or labels (like aws LB annotations, etc) from the helm values/helm chart

**Comment by EItanya** [comment]
Fixed here by updating skv2 to include custom pod overlays https://github.com/solo-io/gloo-mesh/commit/d86f9e6b008bc5c8a045c72f592f07dec6c636a7
