### ISSUE TITLE
Explicitly document the steps required for registering the management cluster

### ISSUE THREAD

**Issue by joekelley** [solo-io/gloo-mesh#1384]
In the [enterprise installation doc](https://docs.solo.io/gloo-mesh/latest/setup/installation/enterprise_installation/#helm), we have a note describing how users should provide the mgmt cluster's name at install time if the user intends to register it later. We should expand on this documentation or provide a link to describe all the steps for registering the management cluster.

**Comment by chrisgaun** [comment]
Combine or put under same Milestone as the "Improve set up docs" Issue
