### ISSUE TITLE
Python 2 is required to install meshctl

### ISSUE THREAD

**Issue by murphye** [solo-io/gloo-mesh#1386]
**Describe the bug**

I already have Python 3 installed in Ubuntu. However, when I try to install `meshctl` I get this error:

```
curl -sL https://run.solo.io/meshctl/install | sh
Python is required to install meshctl
```

I have to run `sudo apt install python` to install Python 2 to proceed with the `meshctl` installation.

Any modern tool should be using Python 3 at this point.

**Comment by joekelley** [comment]
Gloo recently resolved this: https://github.com/solo-io/gloo/pull/4751/files
