### ISSUE TITLE
Enterprise helm docs do not include descriptions of values inherited from OSS

### ISSUE THREAD

**Issue by joekelley** [solo-io/gloo-mesh#1396]
For example, `disallowIntersectingConfig` has no description here: https://docs.solo.io/gloo-mesh/latest/reference/helm/gloo_mesh_enterprise/v1.0.1/enterprise_networking/ but does have one here: https://docs.solo.io/gloo-mesh/latest/reference/helm/gloo_mesh/v1.0.1/gloo_mesh/

**Comment by ashleywang1** [comment]
It does now:

`disallowIntersectingConfig` shows up both here:
https://docs.solo.io/gloo-mesh/latest/reference/helm/gloo_mesh/1.0/gloo_mesh/
and
https://docs.solo.io/gloo-mesh/latest/reference/helm/gloo_mesh_enterprise/1.0/enterprise_networking/
