### ISSUE TITLE
Expose relay svc as LoadBalancer by default

### ISSUE THREAD

**Issue by rvennam** [solo-io/gloo-mesh#1411]
**Is your feature request related to a problem? Please describe.**
- Manually exposing the svc as a LB or configuring install with a flag leads to bad UX experience.  
- Should not assume that users have Istio on the mgmt cluster to expose using istio ingress

**Describe the solution you'd like**
Expose relay svc as LoadBalancer by default

**Comment by joekelley** [comment]
We should update our docs to reference this as the default once it's done

**Comment by joekelley** [comment]
This will be done in the next release of Gloo Mesh Enterprise, 1.0.4

**Comment by joekelley** [comment]
GME 1.0.4 is now available
