### ISSUE TITLE
Improve output of meshctl cluster deregister

### ISSUE THREAD

**Issue by rvennam** [solo-io/gloo-mesh#1412]
**Is your feature request related to a problem? Please describe.**
When kube context pointed at my mgmt cluster, I want to deregister a cluster. I ran:
```
$ meshctl cluster deregister enterprise remote-cluster2
warning: release enterprise-agent does not exist, nothing to uninstall
```

This output is confusing. The command actually succeeded in deregistering the cluster, but the warning made me think that I ran the command against the wrong cluster. Why was it trying to uninstall the enterprise-agent? Was I meant to set my context to the the remote-cluster? 

Also, 
`meshctl cluster register enterprise` expects you to target the mgmt cluster, which goes against this help output:
```
$ meshctl cluster
Interacting with remote Kubernetes clusters registered to Gloo Mesh
```

**Comment by ashleywang1** [comment]
This might be related to https://github.com/solo-io/gloo-mesh/issues/1376

The correct command to deregister a remote cluster is:

meshctl cluster deregister enterprise $REMOTE_CLUSTER_NAME --remote-context=$REMOTE_CONTEXT --mgmt-context=$MGMT_CONTEXT
Otherwise - we will end up with a partial dereregistration and a bad state.

**Comment by joekelley** [comment]
Cluster deregistration does two things:
- delete the kubernetescluster resource with name `remote-cluster2`
- uninstall the enterprise-agent on the cluster accessible via $REMOTE_CONTEXT

This is unintuitive; we should require that users provide `--remote-context` at deregister time, and document explicitly that it must be the kubeconfig backing `remote-cluster2`.

**Comment by rvennam** [comment]
docs: https://docs.solo.io/gloo-mesh/main/reference/cli/meshctl_cluster_deregister_enterprise/
