### ISSUE TITLE
Annotate all gloo mesh pods to opt out of istio sidecar injection

### ISSUE THREAD

**Issue by joekelley** [solo-io/gloo-mesh#1448]
All Gloo Mesh and Gloo Mesh Enterprise pods should be annotated such that they are not injected with Istio sidecars, i.e with `sidecar.istio.io/inject: "false"`. See https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#more-control-adding-exceptions.

**Comment by ashleywang1** [comment]
Closed https://github.com/solo-io/gloo-mesh-enterprise/pull/432
