### ISSUE TITLE
error messages squelched by errgroup.Group implementation

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo-mesh#1468]
currently when a fatal error occurs in our system, the error may be squelched by another error `context deadline exceeeded` or `context cancelled`. this is because the implementation of `errgroup` which we currently use to schedule goroutines does not guarantee that the error propagated by `(errgroup.Group{}).Wait()` shows the original source error.

we should replace with our own implementation which does not squelch errors

**Comment by EItanya** [comment]
Fixed by https://github.com/solo-io/go-utils/pull/450
