### ISSUE TITLE
Gloo Mesh installation can fail with recent Istio versions

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-mesh#1472]
**Describe the requested changes**
Gloo Mesh installation can fail with recent Istio versions if our latest isn't available in the Google Container Registry yet.  We should specify a preferred version tag in the docs, instead of accepting the default, which can result in failure if istioctl version is not yet present in GCR.

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-mesh/latest/getting_started/managed_kubernetes/#installing-istio

**Workarounds**
1. User comments out `hub:` attribute in docs, causing it to default to docker.io/istio, which will have the latest.
2. User provides a specific `tag:` version.

**Additional context**
Internal Slack reference: https://solo-io-corp.slack.com/archives/CHAC8587L/p1619211071321900

**Comment by joekelley** [comment]
Let's write in 1.8.5 for now.
