### ISSUE TITLE
`meshctl plugin search` with no args does not work as advertised

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-mesh#1489]
**Describe the requested changes**
[This](https://docs.solo.io/gloo-mesh/latest/guides/meshctl_plugins/#search-for-available-plugins) doc section says that `meshctl plugin search` with no args will return a list of all available plugins.  

But this isn't true...
```
% meshctl plugin search
Error: accepts 1 arg(s), received 0
plugin error: exit status 1
```
This doc should be updated with proper syntax.

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-mesh/latest/guides/meshctl_plugins/#search-for-available-plugins

**Additional context**
```
% meshctl version
{
  "client": {
    "version": "1.0.4"
  },
  "server": [
    {
      "namespace": "gloo-mesh",
      "components": [
        {
          "componentName": "enterprise-agent",
          "images": [
            {
              "name": "enterprise-agent",
              "domain": "gcr.io",
              "path": "gloo-mesh/enterprise-agent",
              "version": "1.0.7"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by joekelley** [comment]
I believe this is happening because `meshctl-plugin` v.0.5.1 is installed by default, rather than the true latest which has the fix.

**Comment by ryantking** [comment]
`meshctl plugin search` with no args should work as expected in the latest versions of the plugin manager.
