### ISSUE TITLE
Update Upgrading Doc to not reference pre-GA

### ISSUE THREAD

**Issue by murphye** [solo-io/gloo-mesh#1542]
https://docs.solo.io/gloo-mesh/latest/operations/upgrading/

The doc references Gloo Mesh being pre-GA. That is no longer the case. Has the upgrading situation improved?

**Comment by ashleywang1** [comment]
These are docs to upgrade from v1.1.0-betax to v1.1.x: https://github.com/solo-io/gloo-mesh/pull/1846

From the v1.1.x docs on, this page will be changed.
