### ISSUE TITLE
Support multiple Istio ingress gateway workloads

### ISSUE THREAD

**Issue by harveyxia** [solo-io/gloo-mesh#1611]
- [x] **Discovery:** Support discovering multiple Istio ingress gateway workload IPs
  - [x] Update discovery to capture all externally addressable k8s Services (implemented in https://github.com/solo-io/gloo-mesh/pull/1643)
  - [x] Allow discovering ingress gateway workloads in namespaces other than the hardcoded `istio-system`, [issue here] (https://github.com/solo-io/gloo-mesh-enterprise/issues/664) (implemented in https://github.com/solo-io/gloo-mesh/pull/1643)
  - [x] Mark as deprecated istio ingress gateway discovery settings (implemented in https://github.com/solo-io/gloo-mesh/pull/1643)
- [x] **Networking:** Where relevant in translated outputs, support default behavior of load balancing across those ingress gateway workload IPs, else implement the desired APIs described below:
  - [x] **Virtual Mesh:** [allow selection of desired ingress gateway workloads for a given VM](https://github.com/solo-io/gloo-mesh-enterprise/issues/659)
  - [x] **VirtualGateway:** allow selection of desired ingress gateway for N/S traffic
 - [x] Deprecate usage of old `Mesh.Spec.IngressGatewayInfo` and replace with `Mesh.Status.AppliedEastWestIngressGateway`
- [x] **Docs**:
  - [x] Add docs for new VirtualMesh ingress gateway selector

**Comment by harveyxia** [comment]
Discovery requirements from @christian-posta:

1. We can't assume that all ingress gateway workloads have a common label pair, so we'll need OR semantics between sets of labels
2. We also need to expose ability to configure ingress gateway namespace, currently it's hardcoded to `istio-system`

**Comment by harveyxia** [comment]
When routing to externally accessible services, the `<IP:Port>` pair values depend on the Service type, which has some nuance [described here](https://stackoverflow.com/questions/41509439/whats-the-difference-between-clusterip-nodeport-and-loadbalancer-service-types/41510604#41510604)

**Comment by harveyxia** [comment]
The remaining work is on the VirtualGateway, tracked in this issue, https://github.com/solo-io/gloo-mesh-enterprise/issues/857

**Comment by Sodman** [comment]
All tasks in this list have been completed & merged into main - will be part of 1.1 release.
