### ISSUE TITLE
Broken Link on discovery_intro page

### ISSUE THREAD

**Issue by caleygoff-invitae** [solo-io/gloo-mesh#1633]
**Describe the requested changes**
The sentence on the bottom of the linked page and in the quoted text below appears to be broken. It is relevant to joining meshes across clusters into a VirtualMesh.

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-mesh/latest/guides/discovery_intro/
2. https://docs.solo.io/gloo-mesh/latest/guides/traffic_policy/

**Additional context**

for url 1.
> Now that we have Istio installed, and we've seen Gloo Mesh discover the meshes across different clusters, we can now unify them into a single [Virtual Mesh](https://docs.solo.io/gloo-mesh/latest/reference/api/github.com.solo-io.gloo-mesh.api.networking.v1alpha2.virtual_mesh/). 

for url 2.
> Now that we have seen a simple example of how Gloo Mesh can be used to configure traffic policies, we can expand that vision across multiple clusters in a [Virtual Mesh](https://docs.solo.io/gloo-mesh/latest/reference/api/github.com.solo-io.gloo-mesh.api.networking.v1alpha2.virtual_mesh/). See the guide on establishing shared trust domain for multiple meshes.

**Comment by caleygoff-invitae** [comment]
I _think_ it might be pointed here? https://github.com/solo-io/gloo-mesh/blob/611dea53744ae913b2512bf640cb20e5144f7fec/docs/content/reference/api/github.com.solo-io.gloo-mesh.api.networking.v1.virtual_mesh.md

**Comment by ashleywang1** [comment]
This was fixed on 'main' with this PR: https://github.com/solo-io/gloo-mesh/pull/1655
