### ISSUE TITLE
istio discovery doesn't handle revisions

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo-mesh#1662]
**Describe the bug**
Istio discovery does not properly handle revisions. When searching for a deployment it will look for the hardcoded deployment name `istiod`, however when using revisions, the name will take the form `istiod-<revision-name>`

**To Reproduce**
Install istio with a revision

**Expected behavior**
We can still discovery Istio

**Comment by jahvon** [comment]
Reopening this since the fix didn't fully resolve the issue
