### ISSUE TITLE
Write Gloo Mesh-in-OpenShift installation guide

### ISSUE THREAD

**Issue by mlholland** [solo-io/gloo-mesh#1699]
The extra steps required to get Gloo Mesh working in Openshift are manageable enough that we can explain all of it in a single setup guide. Let's get that written.

See spike issue for initial discussion: https://github.com/solo-io/gloo-mesh-enterprise/issues/624

**Comment by chrisgaun** [comment]
Talk to @djannot on this. He has docs on both air gap and connected installations.
