### ISSUE TITLE
Support wildcard domain name when creating ExternalService Destinations 

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo-mesh#1732]
A User can allow traffic to  *.example.com

**Comment by harveyxia** [comment]
@asayah It looks like this should be working already? We take the ExternalService hosts field and translate it directly to ServiceEntry's hosts field, [see here](https://github.com/solo-io/gloo-mesh-enterprise/blob/f6d74eaa24c95a7b14024851b9684a01090c1997/enterprise-networking/pkg/networking/translator/plugins/istio/external-service/external_service_plugin.go#L194)

**Comment by asayah** [comment]
@harveyxia this is correct, it will work with any host, but this will not work for wildcard addr like *.foo.com the [res](https://github.com/solo-io/gloo-mesh-enterprise/blob/f6d74eaa24c95a7b14024851b9684a01090c1997/enterprise-networking/pkg/networking/translator/plugins/istio/external-service/external_service_plugin.go#L198)  needs to be of type NONE and not DNS

**Comment by harveyxia** [comment]
Makes sense—we'll need to update [this function](https://github.com/solo-io/gloo-mesh/blob/4571cc6fb7505be306429a125e0c6fc60bdf390d/pkg/mesh-networking/translation/istio/destination/federation/federation_translator.go#L395) to return `ServiceEntry_NONE` if any wildcards are encountered in the hosts field. Furthermore, we need to throw an error we encounter a wildcard hostname along with either a regular hostname, ipv4, or ipv6.

**Comment by harveyxia** [comment]
@asayah To clarify, are the wildcards going to be in the ExternalService's [host](https://github.com/solo-io/gloo-mesh/blob/main/api/discovery/v1/destination.proto#L188) field or [addresses](https://github.com/solo-io/gloo-mesh/blob/main/api/discovery/v1/destination.proto#L192) field, or both?

DNS resolution on the ServiceEntry only affects `addresses` (i.e. endpoints), but the host can be an endpoint if:

> NOTE 1: When resolution is set to type DNS and no endpoints are specified, the host field will be used as the DNS name of the endpoint to route traffic to.

**Comment by asayah** [comment]
@harveyxia This is for the addresses,  but yes in the use case with no endpoints are provided then it is for both.
