### ISSUE TITLE
Gloo Mesh provided CA cannot be an intermediate CA

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo-mesh#1733]
**Describe the bug**
When creating a `VirtualMesh` in Gloo Mesh, one of the `SharedTrust` options is a provided CA. This feature will currently only work if the signing CA is the root CA, which is not realistic for most production systems.

The [cert issuer](https://github.com/solo-io/gloo-mesh/blob/32f58383641fb552d7c28b80a24114d3f2db0cdd/pkg/certificates/issuer/translation/cert_issuer_translator.go#L75) , which reads the secret, only reads the [root-cert and key](https://github.com/solo-io/gloo-mesh/blob/be514effc997de318edeea87dc450be0a248be2d/pkg/certificates/common/secrets/cert_secrets.go#L32). However, if the signing CA is not the root, then the new istio intermediate cert will require the root, signingCA, and the newly signed istio CA.

**Comment by chrisgaun** [comment]
Backport to 1.1

**Comment by harveyxia** [comment]
Depends on https://github.com/solo-io/skv2-enterprise/issues/51
