### ISSUE TITLE
Install Istio docs are not correct

### ISSUE THREAD

**Issue by linsun** [solo-io/gloo-mesh#1770]
**Describe the requested changes**
In the installation of Istio page, we ask users to download the latest istioctl and then using an istio operator yaml that has 1.8.5.  This will cause issues for Istio when configuration from 1.10 didn't match 1.8.5's code base.  We had a user reporting this issue and his istio install is not functional.

With Istio, the istioctl provides all the necessary artifacts and charts and the version of istioctl has to match the version you are installing.

**Link to any relevant existing docs**
https://docs.solo.io/gloo-mesh/latest/getting_started/managed_kubernetes/

cc @rvennam @jameshbarton @chrisgaun @jahvon @yuval-k @harveyxia

**Comment by chrisgaun** [comment]
Put it into Triage.

**Comment by jameshbarton** [comment]
Let's be careful not to introduce a regression on #1472 in our fix for this issue.

**Comment by linsun** [comment]
As part of this work, we should also create contents:

- what are the supported versions of Istio for a given Gloo Mesh?
- Are they tested on which Kubernetes versions (Also cloud providers if we have such info)
- Istio binary download/distros (do we provide this?  if not, at the minimum, teach people avail images and how to use them).  I assume we have images for regular, FIPS etc.

**Comment by Rachael-Graham** [comment]
Remove tag from istioop altogether. [Slack discussion](https://solo-io-corp.slack.com/archives/CHAC8587L/p1632923558416000)

Ram Vennam 4 hours ago
https://docs.solo.io/gloo-mesh-enterprise/latest/getting_started/managed_kubernetes/
The IstioOperator specifies tag: 1.8.5, but we don't tell the user to download the istioctl 1.8.5...they will likely end up with 1.10 or 1.11 istioctl . Installing Istio 1.8.5 using a istioctl 1.10+ results in a broken istio installation. 1. We should have the user download the matching version. 2. Let's update the tag to 1.10

Will McKinley  4 hours ago
Should we remove that line from the IstioOperator spec?

Ram Vennam  4 hours ago
actually. ya. i agree - just remove that tag and just have user download whatever istioctl we want them to.
