### ISSUE TITLE
Community doc url incorrect

### ISSUE THREAD

**Issue by monsteredc** [solo-io/gloo-mesh#1913]
**Describe the requested changes**
Currently clicking the URL https://docs.solo.io/gloo-mesh/latest on the doc page will redirect to https://docs.solo.io/gloo-mesh-enterprise/latest/. Also, when clicking on the `View Latest Docs` button of gloo-mesh on https://docs.solo.io/, the same situation happens. I think they are sharing the same link `https://docs.solo.io/gloo-mesh/latest/`.

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-mesh/latest

**Comment by chrisgaun** [comment]
Hey, the relevant docs were moved to this URL https://docs.solo.io/gloo-mesh-open-source/latest/ We are def going to make them easier to find.
