### ISSUE TITLE
Docs - Clean up meshctl commands to openmeshctl

### ISSUE THREAD

**Issue by Rachael-Graham** [solo-io/gloo-mesh#1915]
As part of 1.2 release in OSS, need to:
- [ ] update all `meshctl` to `openmeshctl`
- [ ] adjust flags and functionality where needed - see https://github.com/solo-io/gloo-mesh/pull/1904 (not yet finished, Shane to ping us when this is completed so we can begin docs work)
- [ ] Reference docs are auto-generated it seems. Shane says we might need to check though how to generate them in case we need to update the text in the descs, flags, etc

**Comment by artberger** [comment]
See related issue: https://github.com/solo-io/gloo-mesh-enterprise/issues/1930

**Comment by Rachael-Graham** [comment]
dupe of [#1930](https://github.com/solo-io/gloo-mesh-enterprise/issues/1930)
