### ISSUE TITLE
Support TLS Origination to external services specified via wildcard domains

### ISSUE THREAD

**Issue by dthorsen** [solo-io/gloo-mesh#1927]
**Is your feature request related to a problem? Please describe.**
We would like to be able to specify wildcard domains to upgrade egress plaintext HTTP connections with [Istio TLS Origination](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-tls-origination/) feature so that we can ensure egress traffic to specific domains is encrypted in transit.

**Describe the solution you'd like**
Support for https://github.com/istio/istio/issues/10041
We would like to be able to use Istio ServiceEntries, DestinationRules, and VirtualServices to change the destination port from 80 to 443, the TLS mode to SIMPLE, SNI passed from Host/Authority header, and certificate SAN validation based on original Host/Authority header for egress connections to external services matching specified domain suffixes.

**Describe alternatives you've considered**
Contribute this functionality ourselves to upstream Istio and Envoy.

**Additional context**

**Comment by chrisgaun** [comment]
On it

**Comment by chrisgaun** [comment]
@dthorsen When you try the above and confirms it will work we will put it in the product.

**Comment by juli-vert** [comment]
Hi Chris, we tested it and it works, we added another filter to the Virtual level to strip the XFP and it works as expected as well.
  ```
  - applyTo: VIRTUAL_HOST
    match  
      routeConfiguration:  
        vhost:  
          name: '*.nr-ops.net:80'
          route:
          name: default
    patch:
      operation: MERGE
      value:
        request_headers_to_remove: [x-forwarded-proto]```

**Comment by chrisgaun** [comment]
@juli-vert thanks. Will work on getting it into the product for you in August.

**Comment by josh-pritchard** [comment]
Will release in `v2.1.0-beta15`
