### ISSUE TITLE
meshctl check registration document reference broken

### ISSUE THREAD

**Issue by nickschuetz** [solo-io/gloo-mesh#1936]
### Version

1.2.x (latest stable)

### Describe the requested changes

The following link is broken in `meshctl check` output:

```
🟡 Gloo Mesh Agents Connectivity
    Hints:
    * No registered clusters detected. To register a remote cluster that has a deployed Gloo Mesh agent, add a KubernetesCluster CR.
      For more info, see: https://docs.solo.io/gloo-mesh-enterprise/latest/setup/cluster_registration/enterprise_cluster_registration/
```

### Link to any relevant existing docs

1. Broken: https://docs.solo.io/gloo-mesh-enterprise/latest/setup/cluster_registration/enterprise_cluster_registration/
2. Existing location: https://docs.solo.io/gloo-mesh-enterprise/latest/setup/enterprise_cluster_registration/

**Comment by Rachael-Graham** [comment]
https://github.com/solo-io/gloo-mesh-enterprise/commit/0f49dfe8f088d3893c6ed3f5019fe690531b45b3
