### ISSUE TITLE
Docs (Reference Section)

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo-mesh#516]
The reference section of the documentation should mostly be filled with auto generated docs for:
- [x] CLI
- [x] API
- [ ] Helm Values
- [x] Changelog

See [gloo](https://github.com/solo-io/gloo) for more info on how these systems work.

**Comment by joekelley** [comment]
Closing in favor of https://github.com/solo-io/gloo-mesh/issues/1160 and https://github.com/solo-io/gloo-mesh/issues/1161
