### ISSUE TITLE
Change Istio TLS mode depending on remote mesh type

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo-mesh#527]
We're currently hardcoding `TLSSettings_ISTIO_MUTUAL` as the TLS type on the DestinationRule in the client cluster. This won't be correct when we expand to other meshes

**Comment by joekelley** [comment]
We now expose a global default mTLS setting on the Settings CRD as well as on the TrafficPolicy: https://github.com/solo-io/gloo-mesh/blob/v0.11.0/api/networking/v1alpha2/traffic_policy.proto#L87
