### ISSUE TITLE
Improve kubernetes cluster name validation at registration time

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo-mesh#533]
We should improve our cluster name validation at cluster registration time. Currently, providing a non-k8s-compliant name will result in the installation of all agent charts but will fail when provisioning the remote service account.

```shell
❯ meshctl cluster register --cluster-name cluster1ASD--
INFO[0005] finished installing chart as release: agent-crds
INFO[0008] finished installing chart as release: cert-agent
INFO[0011] finished installing chart as release: wasm-agent
Error: ServiceAccount "cluster1ASD--" is invalid: metadata.name: Invalid value: "cluster1ASD--": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

We should also prevent users from registering two clusters with the same name. We can do this by checking whether a kubernetes cluster resource exists with the same provided name. However, we should allow users to pass an `--overwrite` or similar flag and/or be prompted to confirm the action in case they would like to overwrite the existing registered cluster.

**Comment by joekelley** [comment]
validation is handled in [skv2](https://github.com/solo-io/skv2/blob/c04fca339e8a4ddfb8ed68fb6f237d72da18d29a/pkg/multicluster/register/interfaces.go#L93)
