### ISSUE TITLE
un-nest HTTP Method in TrafficPolicy HTTP Matcher, convert to string

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo-mesh#538]
currently, request matcher requires the user to write something like this:

```
method:
  method: GET
```

which forces a redundant level of nesting just so we can make our code use an Enum and be nullable. While I appreciate the stronger guarantees this makes for our own code, I'd like to see the user experience look like this:

```
method: GET
```

in other words, i don't think we should place additional burden on our users just to make the work on our backend (slightly) less complicated.

after discussing with @harveyxia I think we should revert the HTTP Method matcher to a string and perform manual validation in the translator (rather than relying on the `jsonpb` parser, which currently performs validation when parsing the enum itself).

**Comment by joekelley** [comment]
done in https://github.com/solo-io/gloo-mesh/pull/1287/files#diff-41d76041a6ae498319dbcb47496b7d097fff108471ff618e43a8c1a062953951R61
