### ISSUE TITLE
Docs release process (latest)

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo-mesh#545]
When a new release is cut (e.g. 0.7.1 -> 0.7.2) an additional commit must be merged to package 0.7.2 docs. See https://github.com/solo-io/service-mesh-hub/commit/c5c3c19a66d574e769cf32bb913e40368a2f1cce#diff-366e6256bfcf6bf1aae5ee7b9e343475

We should automate this process such that versioned docs are updated on release.

**Comment by joekelley** [comment]
Generate the `version.json` file in the docsgen step; have it read the latest patch of all minors starting with some fixed version (maybe 0.7.x). 

We should be mindful of when the script runs, whether that be on commit or on release.
