### ISSUE TITLE
Design story for SMH cloud-provider account permissions

### ISSUE THREAD

**Issue by harveyxia** [solo-io/gloo-mesh#684]
Integrating SMH with a cloud-provider entails the user granting SMH access to that cloud-provider account.

1. We need a way to surface to the user exactly what permissions are needed by SMH for the SMH functionality that the user has enabled.

2. We also need to understand how the user would like to model those permissions in terms of accounts—do they grant SMH access to a single account that contains all necessary permissions? Or would they want to split that set of permissions across multiple accounts with finer-grained access and SMH uses different accounts for different functions?

**Comment by joekelley** [comment]
Closing for now as this is a subtask as a larger story we won't be taking on in the short-term https://github.com/solo-io/gloo-mesh/issues/524
