### ISSUE TITLE
Docs: Make note of CSR incompatibility between Istio 1.5 and k8s 1.18

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/gloo-mesh#700]
Relevant Istio issue: https://github.com/istio/istio/issues/22215

Encountered while following our "Installing Istio" guide

**Comment by GrahamGoudeau** [comment]
@christian-posta

**Comment by joekelley** [comment]
[Istio 1.5 is EOL](https://istio.io/latest/news/support/announcing-1.5-eol/#:~:text=According%20to%20Istio's%20support%20policy,end%20on%20August%2021st%2C%202020.)
