### ISSUE TITLE
Handle k8s clusters with non-default domain name

### ISSUE THREAD

**Issue by harveyxia** [solo-io/gloo-mesh#756]
Handle the issue described here, https://github.com/knative/eventing/issues/714. We can either require the user to declare their non-default domain name in a relevant SMH CRD, or we can infer it during discovery with [the logic here](https://github.com/knative/pkg/blob/b79e4a24ca506bebf936db155602b757c4d7bc43/network/domain.go#L45), i.e. looking at the `/etc/resolv.conf` present on every container in the cluster.

The second approach is complicated by having to introspect a container running on the remote cluster, which discovery currently does not do.

**Comment by joekelley** [comment]
The user can provide a cluster domain override at registration time and it will be recorded on the KubernetesCluster resource.
