### ISSUE TITLE
Allow Istio certs to be managed outside of smh

### ISSUE THREAD

**Issue by nea1** [solo-io/gloo-mesh#803]
**Is your feature request related to a problem? Please describe.**
SMH currently supports either a provided root cert to the virtualmesh, or the user can specify for it to create one. Individual Istios then receive an intermediate cert created from this. This ensures a common trusted root between all istios in the virtualmesh. 
To aid migration and support different infrastructure setups, a third option where smh does not manage the individual Istio certs at all would be useful. For example cert-manager may already be used in an infrastructure to ensure a common root of trust between istios. Currently migrating such clusters to smh would require rotating all the certs - including the intermediate - this is potentially a non-trivial operation. Allowing the external creation/management of Istio certs would also let users manage their istio certs inline with others certs in the cluster.

**Describe the solution you'd like**
An option in `virtualmesh` to specify that a common root of trust has been established outside of smh (or simply make `certificateAuthority` an optional field)

**Comment by christian-posta** [comment]
Agreed! We'll add this to our list of things to track to get done in the near term. Thanks for opening this!

**Comment by EItanya** [comment]
This is already supported today. Set the following value to `nil` in the Virtual Mesh: https://docs.solo.io/gloo-mesh/main/reference/api/github.com.solo-io.gloo-mesh.api.networking.v1.virtual_mesh/#networking.mesh.gloo.solo.io.VirtualMeshSpec.MTLSConfig
