### ISSUE TITLE
VirtualMesh Restrictive Federation

### ISSUE THREAD

**Issue by nea1** [solo-io/gloo-mesh#804]
**Is your feature request related to a problem? Please describe.**
SMH currently creates ServiceEntries, DestinationRules & Gateway resources for _all_ services in _all_ other clusters in the mesh.
In a mesh of say 6 clusters running 500 workloads each then this is 5 (number of other clusters) x 500 = 2500 serviceentries created in each cluster. 
Firstly are there any sort of resource/scaling/performance issues that would be hit with approach? Even if not, it does seem quite noisy. For example if only a handful of workloads are desired to be shared across clusters then this is a lot of noise when for example debugging a routing issue. 

**Describe the solution you'd like**
One approach would be to add annotations or labels on kubernetes `services` and/or `namespaces` to indicate that a service (or services if on a namespace) are indeed a `meshservice` and should be made available across clusters in the mesh. Any services/namespaces not labelled would not be federated. An option on `VirtualMesh` would be required to switch between this mode and the current standard 'federate everything' mode.

**Comment by harveyxia** [comment]
Hey Neal, this issue should be addressed once we design and implement "restrictive" federation which will allow for, as you describe, a way to specify which services should be federated to which clusters.
