### ISSUE TITLE
Observability in Service Mesh Hub

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo-mesh#808]
**Is your feature request related to a problem? Please describe.**

When running service meshes in multiple clusters / heterogenous environments, disparate sets of metrics are produced which could be aggregated and correlated using Service Mesh Hub. Currently, hub users must manually inspect metrics produced by different meshes.

**Describe the solution you'd like**
Service Mesh Hub should aggregate metrics, e.g. using Prometheus Federation & similar approaches for centralized access by users. 

Service mesh hub can also address observability concerns by adding its cross-mesh context to the mutli-mesh metrics. For example, it would be 

**Additional context**

Let's use this issue to track proposals regarding the overall centralized Metrics/Observability story for Service Mesh Hub

**Comment by harveyxia** [comment]
We'll be tracking this ongoing epic using the "Area: Metrics" label
