### ISSUE TITLE
Update 3 Cluster Image on SMH docs

### ISSUE THREAD

**Issue by bettyjunod** [solo-io/gloo-mesh#925]
https://docs.solo.io/service-mesh-hub/main/

https://docs.solo.io/service-mesh-hub/main/setup/
The first image on the page needs to be updated to this one.
<img width="567" alt="SMH Diagram-3 Clusters" src="https://user-images.githubusercontent.com/10804749/91608389-53ad8380-e92a-11ea-9c2a-22554b959d37.png">

The second image also needs to be updated -- to this image https://github.com/solo-io/service-mesh-hub/issues/921

**Comment by joekelley** [comment]
all set
