### ISSUE TITLE
Rate Limiting Support for east west traffic

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo-mesh#991]
**Is your feature request related to a problem? Please describe.**
It would be nice if SMH supported rate limiting for the various services participating in a `VirtualMesh`

**Describe the solution you'd like**
Some type of rate limiting API, possibly similar to Gloo Enterprise's rate limiting features

**Comment by Sodman** [comment]
Will re-use the same Gloo Rate Limiting API used by North-South Rate liming in the ingress gateway context - https://github.com/solo-io/gloo-mesh-enterprise/issues/526

**Comment by Sodman** [comment]
Tentatively Sizing as an M, assuming we don't need any API changes. Should do a brief (<1 day) spike before picking this up to confirm existing API can work unmodified.

**Comment by harveyxia** [comment]
Closed source issue here: https://github.com/solo-io/gloo-mesh-enterprise/issues/843

**Comment by chrisgaun** [comment]
Moving to Blocked as the Closed Source issue is in Progress. @npolshakova can close out both when other one is done.

**Comment by Sodman** [comment]
Duplicate of https://github.com/solo-io/gloo-mesh-enterprise/issues/843
