### ISSUE TITLE
Cluster registration with Helm

### ISSUE THREAD

**Issue by m0ps** [solo-io/gloo-mesh#998]
Public documentation describes how to install smh with Helm. I'm wondering how to register cluster in smh with Helm as well? It will be extremely useful from automation purposes (including it as a step in terraform).

**Comment by m0ps** [comment]
Any advice?

**Comment by EItanya** [comment]
Hello, this is now supported, see [here](https://docs.solo.io/gloo-mesh/main/setup/cluster_registration/enterprise_cluster_registration/#register-with-helm)
